apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-api-deployment
  labels:
    app: todo-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-api
  template:
    metadata:
      labels:
        app: todo-api
    spec: 
      containers:
      - name: todo-api
        imagePullPolicy: Always
        image: <OCIR_REGION>/<REPOSITORY_NAME>/todo-api:latest
      imagePullSecrets:
      - name: ocirsecret